[tox]
requires =
    tox>=4
    tox-poetry-install>=0.1.0
env_list = docs, py{39,310,311,312}-django{42,50}-matplotlib{39,38}-numpy{20,126}
isolated_build = true

[gh]
python =
    3.12 = py312, django{42,50}-matplotlib{39,38}-numpy{20,126}
    3.11 = py311, django{42,50}-matplotlib{39,38}-numpy{20,126}
    3.10 = py310, django{42,50}-matplotlib{39,38}-numpy{20,126}
    3.9 = py39, django{42,50}-matplotlib{39,38}-numpy{20,126}

[pytest]
DJANGO_SETTINGS_MODULE = test_app.settings
pythonpath = . test_app
testpaths = test_app/plottings_tests/tests
addopts = -v --tb=short

[testenv]
usedevelop = false
changedir = test_app
commands = pytest
deps = 
    pytest>=8
    pytest-django>=4.8
install_command = poetry install --no-dev {opts} {packages}

[testenv:docs]
deps = 
    sphinx
    sphinx_rtd_theme
changedir = docs
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees . {envtmpdir}/html
install_command = poetry install --only docs {opts} {packages} 
